// Code generated by mockery v2.46.2. DO NOT EDIT.

package endpoint

import (
	context "context"
	model "swearBot/internal/services/checker/model"

	mock "github.com/stretchr/testify/mock"
)

// MockCheckerService is an autogenerated mock type for the CheckerService type
type MockCheckerService struct {
	mock.Mock
}

// CheckMessage provides a mock function with given fields: _a0, _a1
func (_m *MockCheckerService) CheckMessage(_a0 context.Context, _a1 model.CheckMessageReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CheckMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CheckMessageReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCheckerService creates a new instance of MockCheckerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckerService {
	mock := &MockCheckerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
