// Code generated by mockery v2.46.2. DO NOT EDIT.

package service

import (
	context "context"
	model "swearBot/internal/services/statistic/model"

	mock "github.com/stretchr/testify/mock"
)

// MockStatisticRepository is an autogenerated mock type for the StatisticRepository type
type MockStatisticRepository struct {
	mock.Mock
}

// SaveStatistic provides a mock function with given fields: _a0, _a1
func (_m *MockStatisticRepository) SaveStatistic(_a0 context.Context, _a1 model.SaveStatisticsReq) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveStatistic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SaveStatisticsReq) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStatisticRepository creates a new instance of MockStatisticRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatisticRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatisticRepository {
	mock := &MockStatisticRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
