name: test deploy

on:
  push:
    branches:
    - release/*
    - hotfix/*
    paths:
      - 'swear/**'

jobs:
  general-deploy-pipeline:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service_port: 8089
      service_name: swear
      test_suffix: -test
      command_args: -log-format=json -env-mode=test
    secrets: inherit
